apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    admission.datadoghq.com/enabled: "true"
    admission.datadoghq.com/config.mode: "hostip"
    app: v3-frontend-advertiser
    tags.datadoghq.com/env: production
    tags.datadoghq.com/service: v3-frontend-advertiser
    tags.datadoghq.com/version: "1"
  name: v3-frontend-advertiser
  namespace: v3
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: v3-frontend-advertiser
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        # ad.datadoghq.com/v3-frontend-advertiser.logs: | 
        #   [
        #     {
        #       "source":"container",
        #       "service":"v3-frontend-advertiser"
        #     }
        #   ]
        tags.datadoghq.com/env: production
        tags.datadoghq.com/service: v3-frontend-advertiser
        tags.datadoghq.com/version: "1"
      labels:
        app: v3-frontend-advertiser
    spec:
      containers:
      - env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: DD_ENV
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['tags.datadoghq.com/service']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['tags.datadoghq.com/version']
        image: 684661340622.dkr.ecr.us-east-1.amazonaws.com/v3-frontend-advertiser-prod:21
        imagePullPolicy: Always
        name: v3-frontend-advertiser
        ports:
        - containerPort: 80
          name: nginx
          protocol: TCP
        - containerPort: 8080
          name: node
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
