apiVersion: batch/v1
kind: CronJob
metadata:
  name: postback-cron-pixel
  namespace: v3
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: cron-batch-job
        spec:
          containers:
          - command:
            - /usr/bin/php
            - artisan
            - pixel:queue
            image: 684661340622.dkr.ecr.us-east-1.amazonaws.com/postback
            imagePullPolicy: Always
            name: postback
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 15
  schedule: 0/10 * * * *
  successfulJobsHistoryLimit: 1
  suspend: false
