apiVersion: batch/v1
kind: CronJob
metadata:
  annotations: {}
  name: conversor-php-cron-postback-send-laravel
  namespace: v3
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /usr/bin/php
            - artisan
            - postback:send
            image: 684661340622.dkr.ecr.us-east-1.amazonaws.com/conversor-php:latest
            imagePullPolicy: Always
            name: conversor-php
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 15
  schedule: 0/1 * * * *
  successfulJobsHistoryLimit: 1
  suspend: false
