apiVersion: batch/v1
kind: CronJob
metadata:
  annotations: {}
  name: reports-cron-consolidate-clicks
  namespace: v3
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 0
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - "2022-03-30"
            - "2022-03-31"
            - "100000"
            command:
            - /usr/bin/php
            - artisan
            - consolideClicks:init
            image: 684661340622.dkr.ecr.us-east-1.amazonaws.com/reports:latest
            imagePullPolicy: Always
            name: reports
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 15
  schedule: 0 12 13 5 *
  successfulJobsHistoryLimit: 1
  suspend: true
