apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: postback
  name: postback-service
  namespace: v3
spec:
  clusterIP: 172.20.38.230
  clusterIPs:
  - 172.20.38.230
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-to-80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 8093-to-8093-tcp
    port: 8093
    protocol: TCP
    targetPort: 8093
  selector:
    app: postback
  sessionAffinity: None
  type: ClusterIP
