apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: conversor-go
  name: conversor-go-service
  namespace: v3
spec:
  clusterIP: 172.20.16.183
  clusterIPs:
  - 172.20.16.183
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-to-80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: conversor-go
  sessionAffinity: None
  type: ClusterIP
