apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: porteira
  name: porteira-service
  namespace: v3
spec:
  clusterIP: 172.20.167.114
  clusterIPs:
  - 172.20.167.114
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-to-80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 8090-to-8090-tcp
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: porteira
  sessionAffinity: None
  type: ClusterIP
