apiVersion: batch/v1
kind: CronJob
metadata:
  name: advertise-cron-laravel
  namespace: cronjobs-v3
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /usr/bin/php
            - artisan
            - schedule:run
            image: 684661340622.dkr.ecr.us-east-1.amazonaws.com/advertise:latest
            imagePullPolicy: Always
            name: advertise
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 15
      ttlSecondsAfterFinished: 120
  schedule: 0/1 * * * *
  successfulJobsHistoryLimit: 1
  suspend: false
