apiVersion: batch/v1
kind: CronJob
metadata:
  annotations: {}
  name: conversor-php-emailmkt-cron-laravel
  namespace: cronjobs-v3
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /usr/bin/php
            - artisan
            - emailmkt:create
            image: 684661340622.dkr.ecr.us-east-1.amazonaws.com/conversor-php:latest
            imagePullPolicy: Always
            name: conversor-php
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 15
      ttlSecondsAfterFinished: 120
  schedule: 0/1 * * * *
  successfulJobsHistoryLimit: 1
  suspend: true
