apiVersion: batch/v1
kind: CronJob
metadata:
  name: conversor-php-cron-postback-send-laravel
  namespace: cronjobs-v3
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /usr/bin/php
            - artisan
            - postback:send
            image: 684661340622.dkr.ecr.us-east-1.amazonaws.com/conversor-php:latest
            imagePullPolicy: Always
            name: conversor-php-cron-postback-send-laravel
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/www/html/storage/logs
              name: conversor-php-cron-postback-send-laravel
          - command:
            - sh
            - -c
            - sleep 60; tail -n 10000 /var/www/html/storage/logs/laravel.log
            image: alpine:latest
            imagePullPolicy: Always
            name: laravel-logs-cron-postback-send-laravel
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/www/html/storage/logs
              name: conversor-php-cron-postback-send-laravel
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 15
          volumes:
          - hostPath:
              path: /var/www/html/storage/logs
              type: ""
            name: conversor-php-cron-postback-send-laravel
      ttlSecondsAfterFinished: 120
  schedule: 0/1 * * * *
  successfulJobsHistoryLimit: 1
  suspend: false