apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    admission.datadoghq.com/enabled: "true"
    admission.datadoghq.com/config.mode: "hostip"
    app: creatives-cron-upload-consume
    tags.datadoghq.com/env: production
    tags.datadoghq.com/service: creatives-cron-upload-consume
    tags.datadoghq.com/version: "1"
  name: creatives-cron-upload-consume
  namespace: cronjobs-v3
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - php 
            - artisan 
            - creative:upload-consume
            image: 684661340622.dkr.ecr.us-east-1.amazonaws.com/criativo:latest
            imagePullPolicy: Always
            name: creatives-cron-upload-consume
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/www/html/storage/logs
              name: creatives-cron-upload-consume
          # - command:
          #   - sh
          #   - -c
          #   - sleep 300; tail -n 10000 /var/www/html/storage/logs/laravel.log
          #   image: alpine:latest
          #   imagePullPolicy: Always
          #   name: laravel-logs-creatives-cron-upload-consume
          #   resources: {}
          #   terminationMessagePath: /dev/termination-log
          #   terminationMessagePolicy: File
          #   volumeMounts:
          #   - mountPath: /var/www/html/storage/logs
          #     name: creatives-cron-upload-consume
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 15
          volumes:
          - hostPath:
              path: /var/www/html/storage/logs
              type: ""
            name: creatives-cron-upload-consume
  schedule: 0/5 * * * *
  successfulJobsHistoryLimit: 1
  suspend: false
