apiVersion: batch/v1
kind: CronJob
metadata:
  annotations: {}
  name: creatives-cron-laravel
  namespace: cronjobs-v3
  labels:
    admission.datadoghq.com/enabled: "true"
    admission.datadoghq.com/config.mode: "hostip"
    app: creatives-cron-laravel
    tags.datadoghq.com/env: production
    tags.datadoghq.com/service: creatives-cron-laravel
    tags.datadoghq.com/version: "1"
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            ad.datadoghq.com/creatives-cron-laravel.checks: |
              {
                "php_fpm": {
                  "init_config": {},
                  "instances": {"status_url":"http://%%host%%/status", "ping_url":"http://%%host%%/ping", "use_fastcgi": false, "ping_reply": "pong"}
                }
              } 
            ad.datadoghq.com/laravel-logs-creatives-cron-laravel.logs: | 
              [
                {
                  "source":"container",
                  "service":"creatives-cron-laravel"
                }
              ]
            ad.datadoghq.com/creatives-cron-laravel.logs: | 
              [
                {
                  "source":"container",
                  "service":"creatives-cron-laravel"
                }
              ]
        spec:
          containers:
          - command:
            - php
            - artisan
            - schedule:run
            image: 684661340622.dkr.ecr.us-east-1.amazonaws.com/criativo:latest
            imagePullPolicy: Always
            name: creatives-cron-laravel
            env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/www/html/storage/logs
              name: creatives-cron-laravel
          - command:
            - sh
            - -c
            - sleep 60; tail -n 10000 /var/www/html/storage/logs/laravel.log
            image: alpine:latest
            imagePullPolicy: Always
            name: laravel-logs-creatives-cron-laravel
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/www/html/storage/logs
              name: creatives-cron-laravel
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 15
          volumes:
          - hostPath:
              path: /var/www/html/storage/logs
              type: ""
            name: creatives-cron-laravel
      ttlSecondsAfterFinished: 120
  schedule: 0/1 * * * *
  successfulJobsHistoryLimit: 1
  suspend: false